package com.cyberoperative.game.engine

/** Every sound cue the simulation can request (§47). The audio layer maps them. */
enum class GameSound {
    PLAYER_SHOT, LANCE, ORB_HIT, ENEMY_HIT, ENEMY_DEATH, ELITE_DEATH, PLAYER_HURT, CRIT,
    FIREWALL_UP, FIREWALL_BREAK, SHIELD_BLOCK, EMP, UPGRADE_SELECTED, LEVEL_COMPLETE,
    PORTAL_OPEN, BOSS_SPAWN, BOSS_PHASE, BOSS_DEATH, CURRENCY, GAME_OVER, EVENT_START,
    REVIVE, UI_CLICK, UI_BACK, BOOT_TICK, ACCESS_GRANTED
}
